---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP FLI Docs
    url: "/index.html"
  - section: release-notes
  - section: san-migration
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
