---
permalink: phases/plan-prepare-phase.html 
sidebar: sidebar 
keywords: plan and prepare phase, foreign lun import, fli, migration planning, test migration, cutover, intercluster lif, iscsi fli, gap analysis, san migration, fc fli, zoning, test migration 
summary: Exécutez une ou plusieurs migrations de test pour confirmer que les baies, le réseau et la structure, la configuration ONTAP et les étapes de correction de l’hôte sont corrects, et pour collecter des échantillons de débit qui peuvent être extrapolés pour la planification de la production. 
---
= Planification de la migration de test et du basculement pour ONTAP Foreign LUN Import (FLI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exécutez une ou plusieurs migrations de test pour confirmer que les baies, le réseau et la structure, la configuration ONTAP et les étapes de correction de l’hôte sont corrects, et pour collecter des échantillons de débit qui peuvent être extrapolés pour la planification de la production.

Une bonne migration de test permet de valider :

* Préparation du backend : l'accessibilité IC LIF, la stabilité des sessions iSCSI et la découverte des LUN externes sont cohérentes sur tous les chemins.
* Exactitude du flux de travail : la création/le démarrage/l’affichage/la finalisation de la relation d’importation (et la vérification facultative) se comporte comme prévu dans le mode sélectionné (en ligne/hors ligne).
* Préparation de l'hôte : les étapes de réanalyse/correction de l'hôte fonctionnent de manière fiable pour le cas d'utilisation cible (par exemple, ESXi VMFS/RDM, Windows autonome/WFC).
* Estimations opérationnelles : le débit observé lors des tests constitue la base la plus réaliste pour estimer la durée de la migration en production et est généralement meilleur que tout benchmark générique.




== Exemple de test de migration avec Hitachi AMS2100

Voici un exemple de migration de test utilisant un Hitachi AMS2100 comme baie étrangère. Selon les baies impliquées, les systèmes d'exploitation hôtes et d'autres variables, vos étapes peuvent être différentes.

L'exemple suivant peut être un guide général des étapes requises pour réaliser les migrations de test. NetApp recommande d'effectuer les migrations de tests le plus tôt possible pour identifier et avoir le plus de temps possible pour résoudre tout problème présenté par les tests. Un test de migration doit être réalisé sur toutes les combinaisons de baies source et de destination avant de procéder aux migrations de production.

.Étapes
. Créez une LUN de test de 2 Go sur la baie source.
+
.. Connectez-vous à Hitachi Storage Navigator Modular en tant que `system`.
.. Sélectionnez *AMS 2100 array*.
.. Cliquez sur *Afficher et configurer la matrice*.
.. Connectez-vous en utilisant `root`.
.. Développez *groupes* et sélectionnez *unités logiques*.
.. Sélectionnez *Create LU* pour créer la LUN test.
.. Créer une LUN test de 2 Go.
.. Cliquez sur *OK*.
.. Ignorez l'affectation de LUN ici et cliquez sur *Fermer*.
.. Vérifiez que le LUN de test a bien été créé.


. Attribuez le LUN de test au groupe d'hôtes créé pour les initiateurs ONTAP.
+
.. Développez *groupes* et sélectionnez *unités logiques*.
.. Sélectionnez *Groupes d'hôtes* pour associer le LUN de test au groupe d'hôtes *cDOT_FLI*.
.. Sélectionnez le groupe d'hôtes *cDOT_FLI* créé à l'étape précédente et cliquez sur *Modifier le groupe d'hôtes*.
.. Choisissez les ports du groupe d'hôtes. Dans cet exemple, nous choisissons *0a*, *0e*, *1a*, *1e*. Sélectionnez l'option *Forced Set to All Selected Ports*.
.. Dans le HDS Storage Navigator, modifiez le groupe hôte.
.. Cliquez sur *Unités logiques* et ajoutez le LUN de test.
.. Cliquez sur *OK* pour mapper la LUN.
.. Sélectionnez *Oui, j'ai lu l'avertissement ci-dessus et voulez modifier le groupe d'hôtes* et cliquez sur *confirmer*.
.. Vérifiez la création du groupe d'hôtes et cliquez sur *Fermer*.


. Vérifiez le LUN test et le mappage entre le stockage source et le stockage de destination, puis importez les LUN étrangères (FLI).
+
.. Connectez-vous au stockage ONTAP via SSH en utilisant l' `admin`utilisateur.
.. Passez en mode *Avancé*.
+
DataMig-cmode::> set -privilege advanced

.. Saisissez « y » lorsqu'on vous demande si vous souhaitez continuer avec les commandes avancées.
.. Détectez la baie source sur ONTAP. Patientez quelques minutes, puis réessayez de détecter la baie source.
+
storage array show

+
Lors de la découverte initiale de la baie de stockage, il est possible que ONTAP n'affiche pas la baie en découvrant automatiquement. Suivez les instructions ci-dessous pour réinitialiser le port de commutateur sur lequel sont connectés les ports d'initiateur ONTAP.

+
Par exemple, les ports initiateurs du cluster DataMig-cmode `0a` et `0b` d'ONTAP sont connectés aux ports Cisco `4/9` et `4/11`. Pour réinitialiser le port `4/9` sur le commutateur Cisco :

+
[listing]
----
conf t
interface fc4/
shutdown
no shutdown
exit
exit
----
+
La réinitialisation d'un port est généralement suffisante. Vérifiez la liste des matrices et les chemins d'accès aux LUN après avoir réinitialisé un port.

.. Vérifiez que la matrice source est détectée par tous les ports initiateurs :
+
storage array config show -array-name HITACHI_DF600F_1

+
[listing]
----
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
.. Répertoriez le LUN de test mappé à partir du stockage Hitachi et vérifiez les propriétés et les chemins du disque :
+
storage disk show -array-name HITACHI_DF600F_1 -instance

+
[listing]
----

                  Disk: HIT-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: HITACHI_DF600F_1
                Vendor: HITACHI
                 Model: DF600F
         Serial Number: 83017542001A
                   UID: 48495441:43484920:38333031:37353432:30303236:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                            Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port     TPGN    Speed  I/O KB/s  IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  --------------  ------  ----   --- -----
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0

Errors:
-

DataMig-cmode::*>
----


. Marquez le LUN source comme étranger à l'aide du numéro de série :
+
storage disk set-foreign-lun { -serial-number 83017542001A } -is-foreign true

+
.. Vérifiez que le LUN source est marqué comme étranger :
+
storage disk show -array-name HITACHI_DF600F_1

.. Liste de tous les tableaux étrangers et de leurs numéros de série :
+
storage disk show -container-type foreign -fields serial-number

+

NOTE: La commande LUN create détecte la taille et l'alignement en fonction du décalage de la partition et crée le LUN en conséquence avec l'argument de disque étranger.



. Créer un volume de destination :
+
vol create -vserver datamig flivol aggr1 -size 10g

. Créer un LUN de test à l'aide d'un LUN externe :
+
lun create -vserver datamig -path /vol/flivol/testlun1 -ostype linux -foreign-disk 83017542001A

+
.. Répertoriez le LUN de test et vérifiez la taille du LUN avec le LUN source :
+
lun show

+

NOTE: Pour une migration FLI hors ligne, la LUN doit être en ligne afin de la mapper sur un groupe initiateur, puis doit être hors ligne avant de créer la relation d'importation de LUN.



. Créer un igroup de test du protocole FCP sans ajouter d'initiateurs :
+
lun igroup create -vserver datamig -igroup testig1 -protocol fcp -ostype linux

. Associez le LUN de test au groupe d'initiateurs de test :
+
lun map -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Mettre le LUN de test hors ligne :
+
lun hors ligne -vserver datamig -path /vol/flivol/testlun1

. Créer une relation d'importation avec le LUN de test et le LUN étranger :
+
lun import create -vserver datamig -path /vol/flivol/testlun1 -foreign-disk 83017542001A

. Démarrer la migration (importation) :
+
lun import start -vserver datamig -path /vol/flivol/testlun1

+
.. Surveillez la progression de l'importation :
+
lun import show -vserver datamig -path /vol/flivol/testlun1

.. Vérifiez que l'importation s'est bien déroulée :
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           import    started
                                                           completed     100
----


. Lancez la tâche de vérification pour comparer les LUN source et de destination. Surveillez la progression de la vérification :
+
lun import verify start -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -path /vol/flivol/testlun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           in_progress     44
----
+
.. Vérifiez que la tâche de vérification est terminée sans erreur :
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           completed      100
----


. Supprimez la relation d'importation pour supprimer la tâche de migration :
+
lun import delete -vserver datamig -path /vol/flivol/testlun1

+
lun import show -vserver datamig -path /vol/flivol/testlun1

. Dissocier le LUN de test du groupe d'initiateurs de test :
+
lun unmap -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Mettre le LUN de test en ligne :
+
lun online -vserver datamig -path /vol/flivol/testlun1

. Indiquez que l'attribut LUN étranger est faux :
+
storage disk modify -serial-number 83017542001A -is-foreign false

+

NOTE: Ne supprimez pas le groupe d'hôtes créé sur le stockage source avec les ports d'initiateur ONTAP. Le même groupe d'hôtes est réutilisé lors des migrations à partir de cette baie source.

. Suppression de la LUN de test du stockage source
+
.. Connectez-vous à Hitachi Storage Navigator Modular en tant que système.
.. Sélectionnez *AMS 2100 array* et cliquez sur *Afficher et configurer la matrice*.
.. Connectez-vous en utilisant `root`.
.. Sélectionnez *Groups*, puis *Host Groups*.
.. Sélectionnez *cDOT_FLI Igroup* et cliquez sur *Modifier le groupe d'hôtes*.
.. Dans la fenêtre Modifier le groupe d'hôtes, sélectionnez tous les ports cibles choisis pour mapper le LUN de test et sélectionnez *Forcer l'ensemble à tous les ports sélectionnés*.
.. Sélectionnez l'onglet *unités logiques*.
.. Sélectionnez le LUN test dans la fenêtre *unités logiques affectées*.
.. Sélectionnez *Remove* pour supprimer le mappage de LUN.
.. Cliquez sur *OK*.


. Ne supprimez pas le groupe d'hôtes et continuez à supprimer la LUN de test.
+
.. Sélectionnez *Unités logiques*.
.. Sélectionnez le LUN de test créé à l'étape précédente.
.. Cliquez sur *Supprimer LUN*.
.. Cliquez sur *confirmer* pour supprimer la LUN test.


. Supprimez la LUN de test sur le stockage de destination.
+
.. Connectez-vous au stockage ONTAP via SSH en utilisant l'utilisateur  `admin`.
.. Mettez hors ligne le LUN de test sur le système de stockage NetApp :
+
lun hors ligne -vserver datamig -path /vol/flivol/testlun1

+

NOTE: Assurez-vous de ne pas sélectionner une autre LUN hôte.

.. Détruisez le LUN de test sur le système de stockage NetApp :
+
lun destroy -vserver datamig -path /vol/flivol/testlun1

.. Mettez hors ligne le volume de test sur le système de stockage NetApp :
+
vol offline -vserver datamig -volume flivol

.. Détruisez le volume de test sur le système de stockage NetApp :
+
vol destroy -vserver datamig -volume flivol




