---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: 'À partir d" ONTAP 9.1, AFF prend en charge FLI. Vous pouvez utiliser FLI pour importer directement des LUN provenant d"autres baies dans des clusters ONTAP .' 
---
= Importation de LUN étrangères pour importer des LUN dans AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir d' ONTAP 9.1, AFF prend en charge FLI. Vous pouvez utiliser FLI pour importer directement des LUN provenant d'autres baies dans des clusters ONTAP .

À partir d' ONTAP 8.3.2, AFF peut prendre en charge FLI avec une demande de variation de processus (PVR) approuvée. Contactez votre équipe commerciale NetApp pour soumettre le PVR à l'approbation. Une fois la demande approuvée, le demandeur, généralement un ingénieur système NetApp , recevra une lettre d'approbation contenant les instructions pour activer la fonctionnalité FLI.

Pour les versions du logiciel ONTAP antérieures à la version 8.3.2, vous devrez préparer les importations FLI sur une paire HA non- AFF sur le même cluster que l' AFF. Une fois la migration terminée, vous pouvez alors utiliser des opérations non perturbatrices (NDO) telles que vol ou LUN move pour déplacer les LUN migrés vers AFF. Si votre cluster AFF ne comporte aucun nœud non- AFF , discutez avec votre équipe commerciale de la possibilité d'emprunter du matériel de secours pour faciliter cela.
