---
permalink: san-migration/concept_fli_zoning_requirements.html 
sidebar: sidebar 
keywords: fli, zoning, requirements 
summary: Un scénario de migration standard utilisant FLI nécessite quatre zones distinctes. Vous devez inclure des ports spécifiques dans chaque zone. 
---
= Exigences de segmentation FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un scénario de migration standard utilisant FLI nécessite quatre zones distinctes. Vous devez inclure des ports spécifiques dans chaque zone.

* Zone 1 : stockage source vers stockage de destination (structure de production A)
+
La zone 1 doit contenir tous les initiateurs de stockage de destination sur tous les nœuds et tous les ports cibles de stockage source de la structure A. Les membres de la zone sont les suivants :

+
** ONTAP -- nœud 1 -- 0a
** ONTAP -- nœud 2 -- 0a
** AMS2100 -- Ctrl0 -- 0a
** AMS2100 -- CTRL1 -- 1a


* Zone 2 : stockage source vers le stockage de destination (structure de production B)
+
La zone 2 doit contenir tous les ports d'initiateur de stockage de destination sur tous les nœuds et tous les ports cible de stockage source dans la structure B. Les membres de la zone 2 sont les suivants :

+
** ONTAP -- nœud 1 -- 0b
** ONTAP -- nœud 2 -- 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- CTRL1 -- 1e


* Zone 3 : stockage hôte à destination (structure de production A)
+
La zone 3 doit contenir le port 1 de l'adaptateur de bus hôte (HBA) et les ports du contrôleur de destination dans la structure de production A. Les membres de la zone 3 sont les suivants :

+
** ONTAP -- lif1
** ONTAP -- lif3
** Hôte -- HBA0


* Zone 4 : stockage hôte à destination (structure de production B)
+
La zone 4 doit contenir le port HBA 2 et les ports du contrôleur de destination dans la structure de production B. Les membres de la zone 4 sont les suivants :

+
** ONTAP -- lif2
** ONTAP -- lif4
** Hôte -- HBA1



