---
permalink: san-migration/concept_lun_requirements_and_limitations.html 
sidebar: sidebar 
keywords: lun, requirements, limitations 
summary: Vos LUN doivent respecter les exigences suivantes avant de procéder à une migration FLI. 
---
= Exigences et limites des LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vos LUN doivent respecter les exigences suivantes avant de procéder à une migration FLI.

* FLI requiert au moins un port FC sur chaque contrôleur et fait MIGRER LES LUN directement en mode initiateur.
* Le LUN étranger doit être marqué comme étranger sur la baie de destination pour empêcher les affectations depuis ONTAP.
* Le LUN étranger doit être en relation d'importation avant de commencer l'importation.
* Le LUN doit avoir la même taille que le LUN étranger. Cette exigence est prise en compte lors des étapes de création du LUN.
* La taille des blocs LUN étrangers doit être de 512 octets. Les LUN NetApp ne prennent en charge que la taille de bloc de 512 octets.
* La LUN ne doit pas être étendue ou sous-traitance.
* La LUN doit être mappée sur au moins un groupe initiateur.
* Le LUN NetApp doit être mis hors ligne avant d'établir une relation. Toutefois, une fois la relation LUN créée, elle peut être remise en ligne en cas de FLI en ligne.




== Limites

* Toutes les migrations se font au niveau des LUN.
* FLI prend uniquement en charge les connexions Fibre Channel (FC).
* FLI ne prend pas en charge les connexions iSCSI directement. Pour que les LUN iSCSI puissent être migrées à l'aide de FLI, le type de LUN doit être modifié en FC. Une fois la migration terminée, le type de LUN est revenir à iSCSI.

