---
permalink: san-migration/concept_performance_enhancements_in_clustered_data_ontap_8_3_1.html 
sidebar: sidebar 
keywords: performance, enhancements, ontap 8.3.1 
summary: 'FLI offre des améliorations visant à mieux gérer les performances et à interrompre le manque de charges de travail. Les améliorations FLI dans ONTAP 8.3.1 incluent une nouvelle commande accélération ainsi que l"importation de LUN qui montrent des améliorations du débit et des groupes de règles de QoS.' 
---
= Améliorations des performances dans ONTAP 8.3.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI offre des améliorations visant à mieux gérer les performances et à interrompre le manque de charges de travail. Les améliorations FLI dans ONTAP 8.3.1 incluent une nouvelle commande accélération ainsi que l'importation de LUN qui montrent des améliorations du débit et des groupes de règles de QoS.

Le `LUN import throttle` la commande est utilisée pour limiter la vitesse maximale à laquelle une importation peut être exécutée.

[listing]
----
cluster::*> lun import throttle -vserver fli_72C -path /vol/flivol/72Clun1 -max-throughput-limit

{<integer>[KB|MB|GB|TB|PB]}  Maximum Throughput Limit (per sec)
----
Utilisez le `instance` passez à l'aide de `lun import show` Pour afficher les informations étendues d'importation des LUN, notamment les informations sur les gaz et la QoS.

[listing]
----
cluster::*> lun import show -instance

    Vserver Name: fli_72C
    LUN Path: /vol/flivol/72Clun1
    Foreign Disk Serial Number: D0i1E+G8Wg6m
    Import Home Node: ontaptme-fc-cluster-01
    Import Current Node: ontaptme-fc-cluster-01
    Operation In Progress: import
    Admin State: stopped
    Operational State: stopped
    Percent Complete: 0
    Blocks Imported: -
    Blocks Compared: -
    Total Blocks: 6297480
    Estimated Remaining Duration: -
    Failure Reason: -
    Maximum Throughput Limit(per sec): -
    Current Throughput (per sec): -
    QoS Policy Group: -
----
Les valeurs de `current throughput` affiche le débit actuel des opérations d'importation ou de vérification. Les utilisateurs doivent le vérifier avant de définir une valeur d'accélérateur. Il est vide lorsqu'il n'est pas en cours d'exécution. Le `QoS policy group` Affiche le groupe QoS si le papillon d'importation de LUN a été utilisé.
