---
permalink: san-migration/create-lun-import-relationship-online.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: 'Avant de migrer un LUN d"une baie étrangère vers un stockage ONTAP , vous devez créer une relation d"importation de LUN. Une relation d"importation de LUN est un appariement permanent entre les stockages source et de destination pour l"importation de données.' 
---
= Créer la relation d'importation LUN pour une migration en ligne ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de migrer un LUN d'une baie étrangère vers un stockage ONTAP , vous devez créer une relation d'importation de LUN. Une relation d'importation de LUN est un appariement permanent entre les stockages source et de destination pour l'importation de données. Les points de terminaison source et de destination sont des LUN.

La création de la relation d'importation de LUN pour les migrations en ligne d'importation de LUN étrangers (FLI) comprend l'identification du LUN étranger à importer à partir de la baie source, la création et la configuration d'un volume de destination pour contenir le LUN étranger, la création du LUN cible de destination et enfin l'établissement de la relation d'importation.



== Étape 1 : Identifier le LUN de la matrice source comme LUN étranger dans ONTAP

Vous devrez identifier le LUN de la matrice source comme un LUN étranger avant de commencer votre migration en ligne FLI.

.Étapes
. Dans ONTAP, modifiez le niveau de privilège sur avancé.
+
[source, cli]
----
set -privilege advanced
----
. Entrez `y` lorsqu'on vous demande si vous souhaitez continuer.
. Vérifiez que la matrice source est visible sur le contrôleur de destination.
+
[source, cli]
----
storage array show
----
+
L'exemple suivant montre la découverte d'un tableau DGC LUNZ.

+
[listing]
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. Affiche les détails de la LUN source.
+
[source, cli]
----
storage array config show -array-name <array_name> -instance
----
+
L'exemple suivant montre les détails du tableau DGC LUNZ.

+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. Vérifiez que la matrice source est détectée par tous les ports d'initiateur.
+
[source, cli]
----
storage array config show -array-name <array_name>
----
+
L'exemple suivant montre la matrice DGC LUNZ découverte via tous les ports initiateurs.

+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
. Répertoriez les LUN mappés à partir du stockage source ; puis vérifiez les propriétés et les chemins du disque.
+
[source, cli]
----
storage disk show -array-name <array_name> -container-type lun
----
+
L'exemple suivant montre les LUN mappés à partir du stockage source.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. Afficher la LUN source
+
[source, cli]
----
storage disk show -array-name <array_name>
----
+
L'exemple suivant montre le LUN source.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. Marquez la LUN source comme étant étrangère.
+
[source, cli]
----
storage disk set-foreign-lun -is-foreign true -disk <disk_name>
----
+
L'exemple suivant montre la commande permettant de marquer le LUN source comme étranger.

+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. Vérifiez que la LUN source est marquée comme étant étrangère.
+
[source, cli]
----
storage disk show -array-name <array_name>
----
+
L'exemple suivant montre le LUN source marqué comme étranger.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. Répertoriez tous les LUN étrangers et leurs numéros de série.
+
[source, cli]
----
storage disk show -container-type foreign -fields serial-number
----
+
Les numéros de série sont utilisés dans les commandes d'importation FLI LUN.

+
L'exemple suivant montre le LUN étranger et son numéro de série.

+
[listing]
----
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----




== Étape 2 : Créer et configurer un volume de destination

Avant de créer la relation d'importation LUN pour une migration en ligne FLI, vous devez créer un volume sur votre système de stockage ONTAP pour contenir le LUN que vous importerez à partir de votre baie étrangère.

.À propos de cette tâche
À partir d' ONTAP 9.17.1, la migration des données des LUN étrangers via la migration hors ligne FLI est prise en charge par les systèmes ASA r2. ASA systèmes diffèrent des autres systèmes ONTAP (ASA, AFF et FAS) par la mise en œuvre de leur couche de stockage. Dans les systèmes ASA r2, les volumes sont automatiquement créés lors de la création d'une unité de stockage (LUN ou espace de noms). Par conséquent, il n'est pas nécessaire de créer un volume avant de créer la relation d'importation de LUN. Vous pouvez ignorer cette étape si vous utilisez un système ASA r2.

En savoir plus sur link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Systèmes ASA r2"^] .

.Étapes
. Créer un volume de destination
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -size <size>
----
. Vérifiez que le volume est créé.
+
[source, cli]
----
volume show -vserver <SVM_name>
----
+
L'exemple suivant montre le volume *fli_vol* créé dans la SVM *fli*.

+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. Définissez l'option fraction_réservation pour chaque volume sur `0` Et définissez la règle Snapshot sur `none`.
+
[source, cli]
----
volume modify -vserver <SVM_name> -volume * -fractional-reserve 0 -snapshot-policy none
----
. Vérifiez les paramètres de volume.
+
[source, cli]
----
volume show -vserver <SVM_name> -volume * -fields fractional-reserve,snapshot-policy
----
+
L'exemple suivant montre l'ensemble *réserve fractionnaire* défini sur  `0` et la *snapshot-policy* définie sur  `none` pour le volume *fli_vol* dans le SVM *fli*.

+
[listing]
----
cluster::*> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. Supprimez toutes les copies Snapshot existantes.
+
[source, cli]
----
set advanced; snap delete –vserver <SVM_name> –vol <volume_name> –snapshot * -force true
----
+
[NOTE]
====
La migration FLI modifie chaque bloc des LUN cibles. Si des copies Snapshot par défaut ou d'autres copies Snapshot existent sur un volume avant la migration FLI, le volume est plein. Modification de la règle et suppression de toute copie Snapshot existante avant la migration FLI La règle Snapshot peut être de nouveau définie après la migration.

====




== Étape 3 : Créer le LUN de destination et la relation d'importation du LUN

Pour préparer votre importation de LUN étranger, créez le LUN et l'igroup de destination, mappez le LUN à l'igroup et créez la relation d'importation de LUN.

A partir d'ONTAP 9.17.1, la migration des données des LUNs étrangères en utilisant la migration hors ligne FLI est prise en charge aveclink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Systèmes ASA r2"^]. Les systèmes ASA r2 diffèrent des autres systèmes ONTAP (ASA, AFF et FAS) par la mise en œuvre de leur couche de stockage. ASA' une unité de stockage (LUN ou espace de noms). Chaque volume ne contient qu'une seule unité de stockage. Par conséquent, pour les systèmes ASA r2, il n'est pas nécessaire d'inclure le nom du volume dans la  `-path` option lors de la création du LUN ; vous devez plutôt inclure le chemin de l'unité de stockage.

.Étapes
. Créez le LUN de destination.
+
[source, cli]
----
lun create -vserver <SVM_name> -path <volume_path|storage_unit_path> -ostype <os_type> -foreign-disk <serial_number>
----
+
[NOTE]
====
Le  `lun create` La commande détecte la taille et l'alignement du LUN en fonction du décalage de partition et crée le LUN en conséquence avec l'option foreign-disk. Certaines E/S apparaîtront toujours comme des écritures partielles et paraîtront donc mal alignées. C'est le cas, par exemple, des journaux de base de données.

====
. Vérifiez que le nouveau LUN est créé.
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
L'exemple suivant montre le nouveau LUN créé dans le SVM *fli*.

+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. Si vous exécutez ONTAP 9.15.1 ou une version ultérieure, désactivez l’allocation d’espace pour les LUN nouvellement créés.
+
L'allocation d'espace est activée par défaut pour les LUN nouvellement créés dans ONTAP 9.15.1 et versions ultérieures.

+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation disabled
----
. Vérifiez que l’allocation d’espace est désactivée.
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. Créez un groupe initiateur de protocole FCP avec des initiateurs hôtes.
+
[source, cli]
----
igroup create -vserver <SVM_name> -igroup <igroup_name> -protocol fcp -ostype <os_type> -initiator <initiator_name>
----
. Vérifiez que l’hôte peut accéder à tous les chemins vers le nouveau groupe i.
+
[source, cli]
----
igroup show -vserver <SVM_name> -igroup <igroup_name>
----
+
L'exemple suivant montre le groupe *FLI* dans la SVM *fli* avec deux initiateurs connectés.

+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. Hors ligne la LUN de destination.
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
L'exemple suivant montre la commande permettant de mettre le nouveau LUN hors ligne dans la SVM *fli*.

+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. Mappez la LUN de destination sur le groupe initiateur.
+
[source, cli]
----
lun map -vserver <SVM_name> -path <volume_path|storage_unit_path> -igroup <igroup_name>
----
. Créer une relation d'importation entre une nouvelle LUN et une LUN étrangère
+
[source, cli]
----
lun import create -vserver <SVM_name> -path <volume_path|storage_unit_path> -foreign-disk <disk_serial_number>
----


.Quelle est la prochaine étape ?
link:map-source-lun-to-destination-online-migration.html["Mapper le LUN source au LUN de destination ONTAP"] .

.Informations connexes
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["En savoir plus sur les E/S non alignées"^] .
