---
permalink: san-migration/task_verifying_source_luns_on_destination_storage_for_offline_foreign_lun_import.html 
sidebar: sidebar 
keywords: verify, source luns, destination storage, offline fli 
summary: 'Dans le cadre du processus d"importation de LUN étrangères hors ligne, vous devez vérifier vos LUN source sur votre système de stockage de destination.' 
---
= Vérification des LUN source sur un système de stockage de destination pour une disponibilité FLI hors ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans le cadre du processus d'importation de LUN étrangères hors ligne, vous devez vérifier vos LUN source sur votre système de stockage de destination.

.Étapes
. Vérifiez les LUN source et le mappage entre le stockage source et le stockage de destination.
. Connectez-vous au stockage ONTAP via SSH à l'aide de l'utilisateur admin.
. Changer le mode sur Avancé : `set -privilege advanced`
. Entrez `y` lorsqu'on vous demande si vous souhaitez continuer.
. Découvrez la baie source sur ONTAP. Attendez quelques minutes et essayez à nouveau de détecter la matrice source. `storage array show`
+
[listing]
----
DataMig-cmode::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
Lors de la découverte initiale de la baie de stockage, il est possible que ONTAP n'affiche pas la baie en découvrant automatiquement. Suivez les instructions ci-dessous pour réinitialiser le port de commutateur sur lequel sont connectés les ports d'initiateur ONTAP.

====
. Vérifiez que la matrice source est détectée par tous les ports d'initiateur.
+
[listing]
----
DataMig-cmode::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
. Répertorie les LUN source mappées à partir du stockage Hitachi. Vérifiez les propriétés et les chemins du disque.
+
Vous devez connaître le nombre de chemins attendus en fonction de votre câblage (au moins deux chemins pour chaque contrôleur source). Vous devez également vérifier le journal des événements après avoir masquant les LUN de la matrice.

+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

DataMig-cmode::*>
----

