---
permalink: san-migration/task_fli_transition_performing_a_disruptive_cutover.html 
sidebar: sidebar 
keywords: perform, disruptive, cutover, fli 7-mode, ontap 
summary: Dans cet exemple, vous suivez les étapes générales pour effectuer une mise en service disruptive pour le processus de transition FLI. 
---
= Effectuer la mise en service disruptive de FLI 7-mode vers ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans cet exemple, vous suivez les étapes générales pour effectuer une mise en service disruptive pour le processus de transition FLI.

Pour une présentation détaillée de la résolution des problèmes liés à l'hôte sur les hôtes Windows, Linux et ESXi, consultez les rubriques connexes de ce guide, ainsi que la documentation du système d'exploitation hôte et du kit de connexion hôte.

.Étapes
. Sur le système 7-mode, affichez le groupe initiateur sur lequel la LUN source est mappée.
+
[listing]
----
stme-7ma> igroup show
    FLI_on_fcp (FCP) (ostype: windows):
        10:00:00:00:c9:e6:e2:79 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:43:70 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:3c:f0 (logged in on: 0c, vtic)
----
+
[NOTE]
====
L'interruption commence immédiatement après l'exécution de la commande unmap. Généralement, la fenêtre d'interruption peut être mesurée en minutes. Le déplacement de l'hôte vers la nouvelle cible NetApp et l'analyse des LUN sont littéralement la durée nécessaire.

====
. Si les LUN en cours d'importation sont pour les hôtes ESXi, consultez et suivez les instructions de la rubrique _ESXi CAW/ATS reponcetement_.
. Utilisez le `unmap` Commande de déplacement de la LUN depuis ses hôtes. (La fenêtre d'interruption commence ici.)
+
[listing]
----
stme-7ma> igroup remove -f FLI_on_fcp 10:00:00:00:c9:e6:e2:79
----
. Vérifiez que les initiateurs hôtes ne sont plus présents.
+
[listing]
----
stme-7ma> igroup show
    FLI_on_fcp (FCP) (ostype: windows):
        50:0a:09:81:00:96:43:70 (logged in on: 0c, vtic)
        50:0a:09:81:00:96:3c:f0 (logged in on: 0c, vtic)
----
. Sur le cluster ONTAP, mettez la LUN de destination en ligne et vérifiez qu'elle est mappée.
+
[listing]
----
cluster::*> lun online -vserver fli_72C -path /vol/flivol/72Clun1

cluster::*> lun show -path /vol/flivol/72Clun1
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             online  mapped   windows_2008
                                                                      3.00GB
----
. Relancez l'analyse des disques de l'hôte ; recherchez le LUN sur la cible ONTAP.
+
[NOTE]
====
La fenêtre d'interruption se termine ici.

====
+
Les LUN sont en ligne et mappées, et les hôtes sont maintenant en train de monter la nouvelle LUN hébergée par ONTAP. Les opérations de lecture sont envoyées via la baie ONTAP vers le LUN source, et les écritures sont écrites sur le nouveau LUN hébergé par ONTAP ainsi que sur le LUN source d'origine. Les LUN source et de destination resteront en synchronisation jusqu'à la fin de la migration et la relation LUN sera interrompue.


