---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 'Une tâche de vérification est facultative, mais recommandée. Il s"agit d"une comparaison bloc par bloc des LUN source et de destination. Vérifier que les tâches prennent presque le même temps ou un peu plus que le temps de migration.' 
---
= Vérifier les résultats de la migration hors ligne ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la migration d'un LUN de la baie distante vers votre système de stockage ONTAP , FLI peut effectuer une comparaison bloc par bloc des LUN source et de destination afin de vérifier que la migration est complète et précise. La vérification de la migration prend environ le même temps (voire légèrement plus) que la migration elle-même.

Une vérification de migration n’est pas requise, mais est fortement recommandée.

.À propos de cette tâche
A partir d'ONTAP 9.17.1, la migration des données des LUNs étrangères en utilisant la migration hors ligne FLI est prise en charge aveclink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Systèmes ASA r2"^]. Les systèmes ASA r2 diffèrent des autres systèmes ONTAP (ASA, AFF et FAS) par la mise en œuvre de leur couche de stockage. ASA' une unité de stockage (LUN ou espace de noms). Chaque volume ne contient qu'une seule unité de stockage. Par conséquent, pour les systèmes ASA r2, il n'est pas nécessaire d'inclure le nom du volume dans la  `-path` option lors de la création du LUN ; vous devez plutôt inclure le chemin de l'unité de stockage.

.Étapes
. Démarrez la vérification de la migration LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Cet exemple montre la commande permettant de démarrer la vérification de la migration LUN pour les LUN nommés *bootlun*, *fdrive* et *gdrive* dans le volume *winvol* et le SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. Surveiller l’état de vérification.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
Cet exemple montre la commande permettant de surveiller l'état de vérification du SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
Vous pouvez exécuter la même commande pour suivre la progression de la vérification. L'état opérationnel affiche le statut « terminé » lorsque la tâche de vérification est terminée avec succès.

. Arrêtez la vérification du LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Cet exemple montre la commande permettant d'arrêter la vérification du LUN pour le SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
La vérification de l'importation du LUN doit être explicitement arrêtée avant de remettre le LUN en ligne. Dans le cas contraire,  `lun online` La commande échoue. Cette étape doit être effectuée manuellement, même si l'état indique que la vérification est terminée.



.Quelle est la prochaine étape ?
link:remove-lun-import-relationship-offline.html["Supprimer la relation d'importation LUN"] .
