---
permalink: san-migration/task_fli_online_preparing_the_lun_path.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: 'Pour préparer la migration FLI en ligne, vérifiez les chemins d"hôtes et LUN source, entre autres.' 
---
= FLI en ligne : préparation du chemin de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour préparer la migration FLI en ligne, vérifiez les chemins d'hôtes et LUN source, entre autres.

.Étapes
. Dans ONTAP, définissez le niveau de privilège sur `advanced`.
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. Vérifiez que la matrice source est visible sur le contrôleur de destination.
+
[listing]
----

        cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. Affiche les détails de la LUN source.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. Vérifiez que la matrice source est détectée par tous les ports d'initiateur.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
+
[NOTE]
====
Le mot Wrapping dans le résultat suivant n'a pas de signification particulière.

====
. Répertoriez les LUN mappées à partir du stockage source. Vérifiez les propriétés et les chemins du disque.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. Afficher la LUN source
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. Marquez la LUN source comme étant étrangère.
+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. Vérifiez que la LUN source est marquée comme étant étrangère.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. Les numéros de série sont utilisés dans les commandes d'importation FLI LUN. Répertoriez tous les LUN étrangers et leurs numéros de série.
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----
. Créer un volume de destination
+
[listing]
----
cluster::*> vol create -vserver fli -volume fli_vol -aggregate aggr1 -size 2t
[Job 13888] Job succeeded: Successful
----
. Vérifiez le volume.
+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. Définissez l'option fraction_réservation pour chaque volume sur `0` Et définissez la règle Snapshot sur `none`.
+
[listing]
----
DataMig-cmode::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. Vérifiez vos paramètres de volume.
+
[listing]
----
DataMig-cmode::> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. Supprimez toutes les copies Snapshot existantes.
+
[listing]
----
DataMig-cmode::> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
La migration FLI modifie chaque bloc des LUN cibles. Si des copies Snapshot par défaut ou d'autres copies Snapshot existent sur un volume avant la migration FLI, le volume est plein. Modification de la règle et suppression de toute copie Snapshot existante avant la migration FLI La règle Snapshot peut être de nouveau définie après la migration.

====
+
[NOTE]
====
La commande LUN create détecte la taille et l'alignement en fonction du décalage de la partition et crée le LUN en conséquence avec l'option de disque étranger. Pour connaître les problèmes d'alignement d'E/S, consultez l'article de la base de connaissances NetApp *qu'est-ce qu'un E/S non aligné ? Notez également que certaines E/S semblent toujours être des écritures partielles et donc mal alignées. Les journaux de base de données en sont quelques exemples.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["Qu'est-ce qu'une E/S non alignée ?"]

. Créer la LUN cible. Le `LUN create` La commande détecte la taille et l'alignement en fonction du décalage de la partition et crée le LUN en conséquence avec l'argument de disque étranger.
+
[listing]
----
cluster::*> lun create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -ostype windows_2008 -foreign-disk 600601603F103100662E70861000E511

Created a LUN of size 1t (1099511627776)
----
. Vérification du nouveau LUN.
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. Créez un groupe initiateur de protocole FCP avec des initiateurs hôtes.
+
[listing]
----
cluster::*> igroup create -vserver fli -igroup FLI -protocol fcp -ostype windows -initiator 10:00:00:00:c9:e6:e2:79
----
. Vérifiez que l'hôte se connecte à tous les chemins vers le nouveau groupe initiateur.
+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. Hors ligne la LUN de destination.
+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. Mappez la LUN de destination sur le groupe initiateur.
+
[listing]
----
cluster::*> lun map -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -igroup FLI
----
. Créer une relation d'importation entre une nouvelle LUN et une LUN étrangère
+
[listing]
----
cluster::*> lun import create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -foreign-disk 600601603F103100662E70861000E511
----

