---
permalink: san-migration/task_fli_transition_importing_the_data.html 
sidebar: sidebar 
keywords: import, data, fli 7-mode, ontap 
summary: 'Ces étapes décrivent l"importation des données d"un LUN source 7-mode vers un LUN de destination ONTAP à l"aide de FLI.' 
---
= Importation des données de FLI 7-mode vers ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ces étapes décrivent l'importation des données d'un LUN source 7-mode vers un LUN de destination ONTAP à l'aide de FLI.

.À propos de cette tâche
A partir d'ONTAP 9.17.1, la migration des données des LUNs étrangères en utilisant la migration hors ligne FLI est prise en charge aveclink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Systèmes ASA r2"^]. Les systèmes ASA r2 diffèrent des autres systèmes ONTAP (ASA, AFF et FAS) par la mise en œuvre de leur couche de stockage. ASA' une unité de stockage (LUN ou espace de noms). Chaque volume ne contient qu'une seule unité de stockage. Par conséquent, pour les systèmes ASA r2, il n'est pas nécessaire d'inclure le nom du volume dans la  `-path` option lors de la création du LUN ; vous devez plutôt inclure le chemin de l'unité de stockage.

.Étapes
. Démarrez l'importation de la migration.
+
[listing]
----
cluster::*> lun import start -vserver fli_72C -path /vol/flivol/72Clun1
----
. Afficher l'état FLI.
+
[listing]
----
cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 import    started
                                                           completed        100
----
+
Si vous voulez vous assurer que la LUN source reste cohérente une fois la migration terminée, vous devez :

+
** Une fois que l'importation est terminée, arrêtez l'hôte.
** Supprimer la relation LUN : `lun import delete -vserver fli_72C -path /vol/flivol/72Clun1`.
+
[NOTE]
====
Rappelez-vous qu'une fois la relation LUN rompue, les LUN risquent de perdre rapidement la synchronisation, car les modifications sont apportées uniquement à la nouvelle LUN. Par conséquent, même s'il est avantageux de conserver un état cohérent dans le cas où vous souhaitez restaurer l'état d'origine, la nouvelle LUN ne sera probablement pas reflétée dans la LUN source.

====
+
[NOTE]
====
Une fois l'importation arrêtée, vous pouvez détruire la relation d'importation sauf si vous avez l'intention de vérifier l'importation.

====



